
from prefect import Flow
from prefect import Parameter
from prefect.tasks.dbt import DbtShellTask
from orchestrator.config import DBT_PROFILES_DIR, HELPER_SCRIPT


task_generic_dbt = DbtShellTask(
    helper_script=HELPER_SCRIPT, 
    profiles_dir=DBT_PROFILES_DIR,
    name="Autogenerated DBT task",
    return_all=True,
    log_stderr=True)


with Flow("Autogenerated flow to run DBT DAGs") as flow_generic_dbt:
    command = Parameter("command")
    task_generic_dbt(command=command)
